import streamlit as st
import faiss
import numpy as np
import re
from io import BytesIO

from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

from pypdf import PdfReader
from docx import Document
from sentence_transformers import SentenceTransformer


# -------------------------
# PAGE CONFIG
# -------------------------

st.set_page_config(
    page_title="DocuMind Pro AI",
    page_icon="📄",
    layout="wide"
)


# -------------------------
# CUSTOM STYLE
# -------------------------

st.markdown("""
<style>

.block-container{
padding-top:2rem;
}

.title{
font-size:64px;
font-weight:900;
background: linear-gradient(90deg,#2563eb,#7c3aed);
-webkit-background-clip:text;
-webkit-text-fill-color:transparent;
margin-bottom:-8px;
}

.subtitle{
font-size:18px;
color:#6b7280;
margin-bottom:25px;
}

.chat-user{
background:#2563eb;
color:white;
padding:14px;
border-radius:14px;
margin:12px 0;
max-width:70%;
margin-left:auto;
}

.chat-bot{
background:#f1f5f9;
padding:14px;
border-radius:14px;
margin:12px 0;
max-width:70%;
border-left:4px solid #2563eb;
}

button[kind="secondary"]{
border-radius:8px;
}

</style>
""", unsafe_allow_html=True)


# -------------------------
# HEADER
# -------------------------

st.markdown("""
<div style="display:flex;align-items:center;gap:14px">

<div style="font-size:42px">📄🤖</div>

<div>

<div class="title">DocuMind Pro AI</div>

<div class="subtitle">
Ask anything from your documents
</div>

</div>

</div>
""", unsafe_allow_html=True)

st.divider()


# -------------------------
# FILE READ FUNCTIONS
# -------------------------

def read_pdf(file):

    reader = PdfReader(file)

    text = ""

    for page in reader.pages:

        content = page.extract_text()

        if content:
            text += content

    return text



def read_docx(file):

    doc = Document(file)

    text = ""

    for para in doc.paragraphs:

        text += para.text + "\n"

    return text



def read_txt(file):

    return file.read().decode("utf-8")


# -------------------------
# SPLIT TEXT INTO SENTENCES
# -------------------------

def split_text(text):

    sentences = re.split(r'[.!?]', text)

    return [s.strip() for s in sentences if len(s.strip()) > 30]


# -------------------------
# CREATE PDF FOR SINGLE ANSWER
# -------------------------

def create_pdf(question, answer):

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer, pagesize=A4)

    styles = getSampleStyleSheet()

    content = []

    content.append(
        Paragraph("DocuMind Pro AI", styles["Title"])
    )

    content.append(Spacer(1, 15))

    content.append(
        Paragraph(f"<b>Question:</b> {question}", styles["Normal"])
    )

    content.append(Spacer(1, 12))

    content.append(
        Paragraph(f"<b>Answer:</b> {answer}", styles["Normal"])
    )

    content.append(Spacer(1, 40))

    content.append(
        Paragraph(
            "Generated by DocuMind Pro AI",
            styles["Italic"]
        )
    )

    doc.build(content)

    buffer.seek(0)

    return buffer


# -------------------------
# CREATE PDF FOR FULL CHAT
# -------------------------

def create_full_chat_pdf(chat_history):

    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer, pagesize=A4)

    styles = getSampleStyleSheet()

    content = []

    content.append(
        Paragraph("DocuMind Pro AI - Chat Export", styles["Title"])
    )

    content.append(Spacer(1, 20))

    q_no = 1

    for role, msg in chat_history:

        if role == "user":

            content.append(
                Paragraph(
                    f"<b>Q{q_no}:</b> {msg}",
                    styles["Normal"]
                )
            )

            content.append(Spacer(1, 10))

        else:

            content.append(
                Paragraph(
                    f"<b>Answer:</b> {msg}",
                    styles["Normal"]
                )
            )

            content.append(Spacer(1, 20))

            q_no += 1


    content.append(Spacer(1, 40))

    content.append(
        Paragraph(
            "Generated by DocuMind Pro AI",
            styles["Italic"]
        )
    )

    doc.build(content)

    buffer.seek(0)

    return buffer


# -------------------------
# SIDEBAR
# -------------------------

with st.sidebar:

    st.header("Settings")

    top_k = st.slider(
        "Answer detail level",
        1,
        5,
        2
    )

    if st.button("Clear Chat"):

        st.session_state.chat = []

    st.info(
        "Upload a document and ask questions."
    )


# -------------------------
# FILE UPLOAD
# -------------------------

uploaded_file = st.file_uploader(
    "Upload document",
    type=["pdf", "docx", "txt"]
)


# -------------------------
# PROCESS DOCUMENT
# -------------------------

if uploaded_file:

    with st.spinner("Reading document..."):

        if uploaded_file.name.endswith(".pdf"):

            text = read_pdf(uploaded_file)

        elif uploaded_file.name.endswith(".docx"):

            text = read_docx(uploaded_file)

        else:

            text = read_txt(uploaded_file)


        sentences = split_text(text)


        model = SentenceTransformer(
            "sentence-transformers/all-MiniLM-L6-v2"
        )


        embeddings = model.encode(sentences)


        dimension = embeddings.shape[1]


        index = faiss.IndexFlatL2(dimension)


        index.add(np.array(embeddings))


    st.success("Document ready")


    # store chat

    if "chat" not in st.session_state:

        st.session_state.chat = []


    # question input

    question = st.chat_input(
        "Ask anything from the document..."
    )


    if question:

        st.session_state.chat.append(
            ("user", question)
        )


        query_embedding = model.encode([question])


        distances, indices = index.search(
            query_embedding,
            top_k
        )


        selected_sentences = []


        for i in indices[0]:

            s = sentences[i]

            if len(s) > 40:

                selected_sentences.append(s)


        answer = ". ".join(
            selected_sentences[:top_k]
        )


        st.session_state.chat.append(
            ("bot", answer)
        )


    # -------------------------
    # SHOW CHAT
    # -------------------------

    for i, (role, msg) in enumerate(
        st.session_state.chat
    ):

        if role == "user":

            st.markdown(
                f'<div class="chat-user">{msg}</div>',
                unsafe_allow_html=True
            )


        else:

            st.markdown(
                f'<div class="chat-bot">{msg}</div>',
                unsafe_allow_html=True
            )


            col1, col2 = st.columns([1, 5])


            # copy icon button

            with col1:

                st.button(
                    "📑",
                    key=f"copy_{i}"
                )


            # pdf download

            with col2:

                pdf_file = create_pdf(
                    st.session_state.chat[i-1][1],
                    msg
                )


                st.download_button(
                    "📥 PDF",
                    pdf_file,
                    file_name=f"DocuMind_answer_{i}.pdf",
                    key=f"download_{i}"
                )


    # -------------------------
    # DOWNLOAD FULL CHAT
    # -------------------------

    if len(st.session_state.chat) > 0:

        st.divider()

        full_pdf = create_full_chat_pdf(
            st.session_state.chat
        )


        st.download_button(
            "⬇ Download Full Chat",
            full_pdf,
            file_name="DocuMind_full_chat.pdf",
            use_container_width=True
        )


# -------------------------
# FOOTER
# -------------------------

st.divider()

st.caption(
    "© 2026 DocuMind Pro AI • Intelligent Document Assistant"
)